services:
  # Frontend service (Nginx serving static files)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"  # Host port 8080 mapped to container port 80
    depends_on:
      - backend
    networks:
      - app-network

  # Backend service (FastAPI)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"  # Expose backend on port 8000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
    networks:
      - app-network

  # MongoDB service
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

# Networks for inter-service communication
networks:
  app-network:
    driver: bridge

# Volumes for persistent MongoDB data
volumes:
  mongodb_data:
