# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: project
type: Opaque
data:
  API_KEY: ZGV2b3BzX2FwaV9rZXk=        # base64 for 'devops_api_key'
  VERSION_TAG: djEuMA==               # base64 for 'v1.0'
