apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: project
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080  # Exposing port 8080 externally
      targetPort: 80  # Map it to 80 to match the container port
  type: ClusterIP  # Internal service accessible within the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: project  # Specify the project namespac
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000  # Exposing backend on port 8000
      targetPort: 8000
  type: ClusterIP  # Internal service accessible within the cluster
---
